### PR TITLE
Allow specifying connectString

### PR DESCRIPTION
**Pull request by cemremengu**
In current implementation, `connectString` cannot be specified due to assertions.

### CODE REVIEW

**Comment by sunfuze** [comment]
please add unit test code

**Comment by cemremengu** [comment]
@sunfuze It keeps rejecting the credentials (looks like it doesn't take the username into account?). I am not very familiar with mysql but I am using `connectString` way with oracle so it should work here as well.

Any ideas what may be wrong?

**Comment by sunfuze** [comment]
https://github.com/tgriesser/knex/blob/master/src/dialects/mysql/index.js#L67 this is how knex create mysql connection.

```javascript
var connection = mysql.createConnection('mysql://user:pass@host/db?debug=true&charset=BIG5_CHINESE_CI&timezone=-0700');
```
this is example using connection string. so you should overwrite client.connection to connection string.

**Comment by cemremengu** [comment]
@sunfuze So looks like `connectString` option is only for `oracledb`. For everything else, like mysql, you specify 
```
  client: {
    dialect: "mysql",
    connection: "mysql://root:@localhost/test"
  },
```

I think the best action here is to just remove the assertions and let the user specify whatever they want, which will fix everything . No need to assert anything since it will crash and tell the user what the error is.

If you agree, I will close this PR and open another one removing assertions for config.

**Pull request closed without merging**
